# This file is auto generate by tools/config/config_prebuilt.py
# version: from 573038(Galaxy Nexus) ==> I9250_D_2.3.61.23(i9250-GN)
# Date: 2014/11/09 02:38

BAIDU_PREBUILT_DIRS += \
    etc/defaultTheme \
    etc/female \
    etc/modules \
    etc/water \
    tts \


BAIDU_PREBUILT += \
    app/BaiYiSearch.apk \
    app/BaiduAccount.apk \
    app/BaiduAntiDisturbance.apk \
    app/BaiduAppSearch.apk \
    app/BaiduBackupRestore.apk \
    app/BaiduBrowser.apk \
    app/BaiduCamera.apk \
    app/BaiduClickSearch.apk \
    app/BaiduClock.apk \
    app/BaiduFlashlight.apk \
    app/BaiduGallery3D.apk \
    app/BaiduInput.apk \
    app/BaiduLightApp.apk \
    app/BaiduMap.apk \
    app/BaiduMusicPlayer.apk \
    app/BaiduNetworkLocation.apk \
    app/BaiduNotepad.apk \
    app/BaiduProxy.apk \
    app/BaiduSecurityCenter.apk \
    app/BaiduSemiView.apk \
    app/BaiduServiceFramework.apk \
    app/BaiduSocialShare.apk \
    app/BaiduSoundRecorder.apk \
    app/BaiduSync.apk \
    app/BaiduSysFramework.apk \
    app/BaiduTheme.apk \
    app/BaiduTts.apk \
    app/BaiduUpdate.apk \
    app/BaiduUserFeedback.apk \
    app/BaiduVideoPlayer.apk \
    app/BaiduWallet.apk \
    app/Calendar.apk \
    app/DynamicPermissionProvider.apk \
    app/Email2.apk \
    app/Exchange2.apk \
    app/FindmeDM.apk \
    app/GameCenter.apk \
    app/HelpBook.apk \
    app/HomePro.apk \
    app/NewPhoneWizard.apk \
    app/NotificationProvider.apk \
    app/OnekeyWidget.apk \
    app/PicoTts.apk \
    app/ResManager.apk \
    app/SearchBox.apk \
    app/Tag.apk \
    app/TrafficMonitor.apk \
    app/Wallpaper.apk \
    app/YellowPageProvider.apk \
    app/Yellowpages.apk \
    app/YiYueDu.apk \
    app/cm-sdk-release.apk \
    app/iReader.apk \
    bin/WordSegService \
    bin/audioloop \
    bin/codec \
    bin/corrupt_gdt_free_blocks \
    bin/decoder \
    bin/gdbserver \
    bin/hostapd_cli \
    bin/http2wormhole \
    bin/keystore_cli \
    bin/pngtest \
    bin/qemu-props \
    bin/qemud \
    bin/r \
    bin/radiooptions \
    bin/record \
    bin/recordvideo \
    bin/set_ext4_err_bit \
    bin/sf2 \
    bin/showlease \
    bin/stagefright \
    bin/stream \
    bin/testid3 \
    bin/udptest \
    bin/wfd \
    bin/wpa_cli \
    etc/bluetooth/main.conf \
    etc/defaultTheme.btp \
    etc/dict.model.utf \
    etc/dp.db \
    etc/female.btp \
    etc/http2wormhole.conf \
    etc/name.model.utf \
    etc/onlinephonebook.db \
    etc/permissions/framework-yi.xml \
    etc/portable_camera.xml \
    etc/raw_yellow_data.db \
    etc/water.btp \
    framework/framework-res-yi.apk \
    framework/framework-yi.jar \
    framework/secondary_framework.jar \
    lib/hw/camera.goldfish.so \
    lib/hw/gps.goldfish.so \
    lib/hw/lights.goldfish.so \
    lib/hw/sensors.goldfish.so \
    lib/libBDVoiceEncoder_V1.so \
    lib/libBDVoiceRecognitionClient_V1.so \
    lib/libBaiyiAcs.so \
    lib/libBaiyiSecurityJni.so \
    lib/libCNPackage.so \
    lib/libENPackage.so \
    lib/libJniWordSegService.so \
    lib/libSafePay_1.so \
    lib/libSpeakerRec.so \
    lib/libWordSegService.so \
    lib/libbd_wsp_v1_0.so \
    lib/libbdocr.so \
    lib/libbdpush_V2_0.so \
    lib/libbdpush_V2_2.so \
    lib/libc_malloc_debug_leak.so \
    lib/libc_malloc_debug_qemu.so \
    lib/libcyberplayer-core.so \
    lib/libcyberplayer.so \
    lib/libejTTS-yi.so \
    lib/libencrypt.so \
    lib/libffmpeg_baidu.so \
    lib/libjni_eglfenceForGallery.so \
    lib/libjni_filtershow_filtersForGallery.so \
    lib/libjni_mosaic_new.so \
    lib/libjni_tinyplanet.so \
    lib/liblocSDK3.so \
    lib/liblocSDK4.so \
    lib/libmtprocessor-jni.so \
    lib/libpagemap.so \
    lib/libpush-socket.so \
    lib/libregister.so \
    lib/libsapi_V5_1.so \
    lib/libshare.so \
    lib/libtmfe30.so \
    lib/libttscompat.so \
    lib/libttspico.so \
    lib/libvoiceSpeechVad.so \
    lib/libwordseg.so \
    lib/libwormjni.so \
    lib/libyi_backup_module.so \
    lib/libyi_compress_module.so \
    lib/libyi_multitheme_module.so \
    media/audio/alarms/Alarm_Beep_01.ogg \
    media/audio/alarms/Alarm_Beep_02.ogg \
    media/audio/alarms/Alarm_Beep_03.ogg \
    media/audio/alarms/Alarm_Buzzer.ogg \
    media/audio/alarms/Alarm_Classic.ogg \
    media/audio/alarms/Alarm_Rooster_02.ogg \
    media/audio/alarms/Barium.ogg \
    media/audio/alarms/HarvestSeasonAlarm.ogg \
    media/audio/alarms/KusoAlarm.ogg \
    media/audio/alarms/RingingAlarm.ogg \
    media/audio/alarms/Scandium.ogg \
    media/audio/alarms/TinkingAlarm.ogg \
    media/audio/notifications/Belch.ogg \
    media/audio/notifications/Bird_OwlCallingHappySad.ogg \
    media/audio/notifications/CATDomestic_SingleMeow.ogg \
    media/audio/notifications/CrowCaws.ogg \
    media/audio/notifications/HarvestSeason_meassage.ogg \
    media/audio/notifications/HorseInterior_Whinny.ogg \
    media/audio/notifications/HorsesWhiney.ogg \
    media/audio/notifications/Instrument_01.ogg \
    media/audio/notifications/Instrument_02.ogg \
    media/audio/notifications/LoveStory_meassage.ogg \
    media/audio/notifications/MeadowLark_HappyChirps.ogg \
    media/audio/notifications/MischievousLaugh.ogg \
    media/audio/notifications/PromptTone_01.ogg \
    media/audio/notifications/PromptTone_02.ogg \
    media/audio/notifications/PromptTone_03.ogg \
    media/audio/notifications/PromptTone_04.ogg \
    media/audio/notifications/SheepBabyCrying_AdultCalling.ogg \
    media/audio/notifications/WaterDrop_01.ogg \
    media/audio/notifications/WaterDrop_02.ogg \
    media/audio/notifications/WaterDrop_03.ogg \
    media/audio/notifications/WaterDrop_04.ogg \
    media/audio/notifications/Whistle_FingersInMouth.ogg \
    media/audio/ringtones/CarmenTunes.ogg \
    media/audio/ringtones/CasualBlues.ogg \
    media/audio/ringtones/ElectricSounds.ogg \
    media/audio/ringtones/HarvestSeason.ogg \
    media/audio/ringtones/InterestingJourney.ogg \
    media/audio/ringtones/LoveStory.ogg \
    media/audio/ringtones/TwinklingNightSky.ogg \
    media/audio/ringtones/WonderfulLife.ogg \
    media/audio/ui/Castor.ogg \
    media/audio/ui/VideoRecord.wav \
    media/audio/ui/calender.WAV \
    media/audio/ui/camera_click.wav \
    media/audio/ui/email.wav \
    media/audio/ui/low_battery.wav \
    media/audio/ui/message_in_operate.wav \
    media/audio/ui/pc_connect.wav \
    media/audio/ui/plug_headset.wav \
    media/audio/ui/ringtone_in_call.wav \
    media/audio/ui/touch.wav \
    media/audio/ui/unlock.wav \
    xbin/[ \
    xbin/[[ \
    xbin/add-property-tag \
    xbin/adjtimex \
    xbin/arp \
    xbin/ash \
    xbin/awk \
    xbin/base64 \
    xbin/basename \
    xbin/bbconfig \
    xbin/blkid \
    xbin/blockdev \
    xbin/brctl \
    xbin/btool \
    xbin/bunzip2 \
    xbin/busybox \
    xbin/bzcat \
    xbin/bzip2 \
    xbin/cal \
    xbin/cat \
    xbin/catv \
    xbin/chattr \
    xbin/check-lost+found \
    xbin/chgrp \
    xbin/chmod \
    xbin/chown \
    xbin/chroot \
    xbin/clear \
    xbin/cmp \
    xbin/comm \
    xbin/cp \
    xbin/cpio \
    xbin/cpustats \
    xbin/crond \
    xbin/crontab \
    xbin/cut \
    xbin/date \
    xbin/dc \
    xbin/dd \
    xbin/depmod \
    xbin/devmem \
    xbin/df \
    xbin/dhdutil \
    xbin/diff \
    xbin/dirname \
    xbin/dmesg \
    xbin/dnsd \
    xbin/dos2unix \
    xbin/du \
    xbin/echo \
    xbin/ed \
    xbin/egrep \
    xbin/env \
    xbin/expand \
    xbin/expr \
    xbin/false \
    xbin/fbsplash \
    xbin/fdisk \
    xbin/fgrep \
    xbin/find \
    xbin/flash_lock \
    xbin/flash_unlock \
    xbin/flashcp \
    xbin/flock \
    xbin/fold \
    xbin/free \
    xbin/freeramdisk \
    xbin/fstrim \
    xbin/fsync \
    xbin/ftpget \
    xbin/ftpput \
    xbin/fuser \
    xbin/getopt \
    xbin/grep \
    xbin/groups \
    xbin/gunzip \
    xbin/gzip \
    xbin/halt \
    xbin/head \
    xbin/hexdump \
    xbin/id \
    xbin/ifconfig \
    xbin/inetd \
    xbin/insmod \
    xbin/install \
    xbin/ionice \
    xbin/iostat \
    xbin/ip \
    xbin/kill \
    xbin/killall \
    xbin/killall5 \
    xbin/latencytop \
    xbin/less \
    xbin/librank \
    xbin/ln \
    xbin/losetup \
    xbin/ls \
    xbin/lsattr \
    xbin/lsmod \
    xbin/lsusb \
    xbin/lzcat \
    xbin/lzma \
    xbin/lzop \
    xbin/lzopcat \
    xbin/man \
    xbin/md5sum \
    xbin/mesg \
    xbin/micro_bench \
    xbin/mkdir \
    xbin/mke2fs \
    xbin/mkfifo \
    xbin/mkfs.ext2 \
    xbin/mkfs.vfat \
    xbin/mknod \
    xbin/mkswap \
    xbin/mktemp \
    xbin/modinfo \
    xbin/modprobe \
    xbin/more \
    xbin/mount \
    xbin/mountpoint \
    xbin/mpstat \
    xbin/mv \
    xbin/nanddump \
    xbin/nandwrite \
    xbin/nbd-client \
    xbin/netstat \
    xbin/nice \
    xbin/nohup \
    xbin/nslookup \
    xbin/ntpd \
    xbin/od \
    xbin/opcontrol \
    xbin/oprofiled \
    xbin/patch \
    xbin/pgrep \
    xbin/pidof \
    xbin/ping \
    xbin/pipe_progress \
    xbin/pkill \
    xbin/pmap \
    xbin/poweroff \
    xbin/printenv \
    xbin/printf \
    xbin/procmem \
    xbin/procrank \
    xbin/ps \
    xbin/pstree \
    xbin/pwd \
    xbin/pwdx \
    xbin/rawbu \
    xbin/rdev \
    xbin/readlink \
    xbin/realpath \
    xbin/renice \
    xbin/reset \
    xbin/resize \
    xbin/rev \
    xbin/rm \
    xbin/rmdir \
    xbin/rmmod \
    xbin/route \
    xbin/run-parts \
    xbin/rx \
    xbin/sane_schedstat \
    xbin/sed \
    xbin/seq \
    xbin/setconsole \
    xbin/setserial \
    xbin/setsid \
    xbin/sh \
    xbin/sha1sum \
    xbin/sha256sum \
    xbin/sha3sum \
    xbin/sha512sum \
    xbin/showmap \
    xbin/showslab \
    xbin/sleep \
    xbin/sort \
    xbin/split \
    xbin/sqlite3 \
    xbin/stat \
    xbin/strace \
    xbin/strings \
    xbin/stty \
    xbin/su \
    xbin/sum \
    xbin/swapoff \
    xbin/swapon \
    xbin/sync \
    xbin/sysctl \
    xbin/tac \
    xbin/tail \
    xbin/tar \
    xbin/taskset \
    xbin/tcpdump \
    xbin/tee \
    xbin/telnet \
    xbin/telnetd \
    xbin/test \
    xbin/tftp \
    xbin/tftpd \
    xbin/time \
    xbin/timeout \
    xbin/top \
    xbin/touch \
    xbin/tr \
    xbin/traceroute \
    xbin/true \
    xbin/ttysize \
    xbin/tune2fs \
    xbin/umount \
    xbin/uname \
    xbin/uncompress \
    xbin/unexpand \
    xbin/uniq \
    xbin/unix2dos \
    xbin/unlzma \
    xbin/unlzop \
    xbin/unxz \
    xbin/unzip \
    xbin/uptime \
    xbin/usleep \
    xbin/uudecode \
    xbin/uuencode \
    xbin/vi \
    xbin/watch \
    xbin/wc \
    xbin/wget \
    xbin/which \
    xbin/whoami \
    xbin/xargs \
    xbin/xz \
    xbin/xzcat \
    xbin/yes \
    xbin/zcat \


BAIDU_PRESIGNED_APPS += \
    BaiYiSearch.apk \
    BaiduAppSearch.apk \
    BaiduBrowser.apk \
    BaiduInput.apk \
    BaiduMap.apk \
    BaiduNetworkLocation.apk \
    Calendar.apk \
    GameCenter.apk \
    SearchBox.apk \
    YiYueDu.apk \
    cm-sdk-release.apk \
    iReader.apk \


 # This is the end.
